import type { ThemeConfig } from 'antd';

export const themeConfig: ThemeConfig = {
  token: {
    colorPrimary: '#00478E',
    colorPrimaryHover: '#0056CC',
    colorPrimaryActive: '#003366',
    colorSuccess: '#52c41a',
    colorWarning: '#faad14',
    colorError: '#ff4d4f',
    colorInfo: '#1890ff',
    colorText: '#1D1D44',
    colorLink: '#1D1D44',
    colorLinkHover: '#00478E',
    colorLinkActive: '#003366',
    fontFamily: '"Lexend", ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, "Noto Sans", sans-serif',
    fontFamilyCode: '"Lexend", ui-monospace, SFMono-Regular, "SF Mono", Monaco, Consolas, "Liberation Mono", "Courier New", monospace',
    borderRadius: 8,
    borderRadiusLG: 12,
    fontSize: 14,
    fontSizeLG: 16,
    fontSizeXL: 18,
    fontSizeHeading1: 32,
    fontSizeHeading2: 24,
    fontSizeHeading3: 20,
    fontSizeHeading4: 16,
    fontSizeHeading5: 14,
    controlHeight: 40,
    controlHeightLG: 48,
    controlHeightSM: 32,
    padding: 16,
    paddingLG: 24,
    paddingSM: 12,
    margin: 16,
    marginLG: 24,
    marginSM: 12,
    boxShadow: '0 2px 8px rgba(0, 0, 0, 0.15)',
    boxShadowSecondary: '0 2px 4px rgba(0, 0, 0, 0.12)',
    boxShadowTertiary: '0 1px 2px rgba(0, 0, 0, 0.08)',
  },
  components: {
    Divider: {
      colorSplit: '#E0E0E0',
    },
    Typography: {
      colorText: '#1D1D44',
      titleMarginBottom: 16,
      titleMarginTop: 0,
      fontFamily: '"Lexend", ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, "Noto Sans", sans-serif',
    },
    Button: {
      borderRadius: 8,
      controlHeight: 40,
      controlHeightLG: 48,
      controlHeightSM: 32,
      paddingInline: 16,
      paddingInlineLG: 24,
      paddingInlineSM: 12,
      fontFamily: '"Lexend", ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, "Noto Sans", sans-serif',
    },
    Input: {
      borderRadius: 8,
      controlHeight: 40,
      controlHeightLG: 48,
      controlHeightSM: 32,
      paddingInline: 12,
      paddingInlineLG: 16,
      paddingInlineSM: 8,
      fontFamily: '"Lexend", ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, "Noto Sans", sans-serif',
    },
    Modal: {
      borderRadius: 12,
      borderRadiusLG: 16,
      padding: 24,
      paddingLG: 32,
      paddingSM: 16,
    },
    Card: {
      borderRadius: 12,
      borderRadiusLG: 16,
      padding: 24,
      paddingLG: 32,
      paddingSM: 16,
    },
    Select: {
      borderRadius: 8,
      controlHeight: 40,
      controlHeightLG: 48,
      controlHeightSM: 32,
      fontFamily: '"Lexend", ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, "Noto Sans", sans-serif',
      colorTextPlaceholder: '#1D1D44',
    },
    Table: {
      borderRadius: 8,
      borderRadiusLG: 12,
    },
    Alert: {
      borderRadius: 8,
      borderRadiusLG: 12,
    },
    Badge: {
      borderRadius: 8,
      borderRadiusLG: 12,
    },
    Form: {
      labelFontSize: 14,
      fontFamily: '"Lexend", ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, "Noto Sans", sans-serif',
    },
    Layout: {
      colorBgContainer: '#ffffff',
      colorBgLayout: '#ffffff',
      headerBg: '#ffffff',
      colorBgSolid: '#ffffff',
      triggerBg: '#ffffff',
    },
    Menu: {
      fontFamily: '"Lexend", ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, "Noto Sans", sans-serif',
    },
  },
}; 