services:
  prosai-client-prod:
    build:
      context: .
      dockerfile: Dockerfile
      target: runner
    container_name: prosai-client-prod
    # ports:
    #   - "3002:3000"
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
    env_file:
      - .env.production
    networks:
      prosai-network:
        ipv4_address: 10.10.10.61
    restart: unless-stopped

networks:
  prosai-network:
    external: true
    name: prosai-network 